services:
  devlabs-k8s:
    build:
      context: .
      dockerfile: devlabs-k8s/.devcontainer/Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity

  devlabs-java:
    image: mcr.microsoft.com/devcontainers/base:noble
    volumes:
      # Mount the root folder that contains .git
      - .:/workspace
    command: sleep infinity